### ISSUE TITLE
unable to swap hot bar with tool belt.

### ISSUE THREAD

**Issue by Sinogard** [milkev/Milkevs-Essentials#2]
i cant seem to get the toolbelt to work even with zero key conflicts. I'm not getting an error in the logs client side or server side... Ill provide them anyway in case there's a hint in there.
logs here https://paste.ee/p/uTVLY

**Comment by milkev** [comment]
it seems to be working fine for me. Its likely a mod conflict. If you can find which mod is causing the issue, I can try to look into it more.
Tested as working with;
Fabric Loader 0.14.9 (1.19.2)
Milkevs Essentials 1.6.0
Trinkets 3.4.0
Cloth Config 8.0.75
Fabric API 0.60.0 (1.19.2)
